/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CosmosButton {
        /**
          * Button shape
          * @default 'normal'
         */
        "shape": 'round' | 'circle' | 'normal';
        /**
          * Button type
          * @default normal
         */
        "type": 'primary' | 'text' | 'normal';
    }
    interface CosmosSelect {
        "todoTitle": string;
    }
}
declare global {
    interface HTMLCosmosButtonElement extends Components.CosmosButton, HTMLStencilElement {
    }
    var HTMLCosmosButtonElement: {
        prototype: HTMLCosmosButtonElement;
        new (): HTMLCosmosButtonElement;
    };
    interface HTMLCosmosSelectElement extends Components.CosmosSelect, HTMLStencilElement {
    }
    var HTMLCosmosSelectElement: {
        prototype: HTMLCosmosSelectElement;
        new (): HTMLCosmosSelectElement;
    };
    interface HTMLElementTagNameMap {
        "cosmos-button": HTMLCosmosButtonElement;
        "cosmos-select": HTMLCosmosSelectElement;
    }
}
declare namespace LocalJSX {
    interface CosmosButton {
        /**
          * Button shape
          * @default 'normal'
         */
        "shape"?: 'round' | 'circle' | 'normal';
        /**
          * Button type
          * @default normal
         */
        "type"?: 'primary' | 'text' | 'normal';
    }
    interface CosmosSelect {
        "todoTitle"?: string;
    }
    interface IntrinsicElements {
        "cosmos-button": CosmosButton;
        "cosmos-select": CosmosSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cosmos-button": LocalJSX.CosmosButton & JSXBase.HTMLAttributes<HTMLCosmosButtonElement>;
            "cosmos-select": LocalJSX.CosmosSelect & JSXBase.HTMLAttributes<HTMLCosmosSelectElement>;
        }
    }
}
