/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CosLogin {
    }
    interface TodoList {
        "todoTitle": string;
    }
}
declare global {
    interface HTMLCosLoginElement extends Components.CosLogin, HTMLStencilElement {
    }
    var HTMLCosLoginElement: {
        prototype: HTMLCosLoginElement;
        new (): HTMLCosLoginElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "cos-login": HTMLCosLoginElement;
        "todo-list": HTMLTodoListElement;
    }
}
declare namespace LocalJSX {
    interface CosLogin {
    }
    interface TodoList {
        "todoTitle"?: string;
    }
    interface IntrinsicElements {
        "cos-login": CosLogin;
        "todo-list": TodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cos-login": LocalJSX.CosLogin & JSXBase.HTMLAttributes<HTMLCosLoginElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
        }
    }
}
